on: push
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        version: [8.0.x, 9.0.x]
    runs-on:  ${{matrix.os}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v4
        with:
          source-url: https://nuget.pkg.github.com/Golos1/index.json
          dotnet-version: ${{matrix.version}}
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_KEY}}
      - run: dotnet build --configuration Release StripeWatch
      - name: Create the package.
        run: dotnet pack --configuration Release StripeWatch
      - run: ls 
      - name: Publish 
        run: dotnet nuget push StripeWatch/bin/Release/*.nupkg

