on: push
jobs:
  build:
    runs-on:  ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v4
        with:
          source-url: https://nuget.pkg.github.com/Golos1/index.json
          dotnet-version: 9.0.x
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_KEY}}
      - run: dotnet build --configuration Release StripeWatch
      - name: Create the package.
        run: dotnet pack --configuration Release StripeWatch
      - run: ls 
      - name: Push Package 
        run: dotnet nuget push StripeWatch/bin/Release/*.nupkg
      - name: Publish
        run: dotnet publish --configuration Release --no-build --output ./publish
      - name: Create Release
        uses: actions/create-release@v1
        env: 
          GITHUB_TOKEN: ${{secrets.RELEASE_TOKEN}}
        with:
          tag_name: ${{github.ref}}
          release_name: Release ${{github.ref}}
      - name: Upload Release files
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{secrets.RELEASE_TOKEN}}
        with: 
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./publish
          asset_name: StripeWatch-${{github.ref}}.zip
          asset_content_type: application/octet-stream
