on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v4
        with:
          source-url: https://nuget.pkg.github.com/Golos1/index.json
          dotnet-version: 9.0.x
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_KEY}}
      - name: Build
        run: dotnet build --configuration Release
      - name: Build solution and generate NuGet package, then push
        run: |
          dotnet pack StripeWatch -c Release 
          find ~/ -name "*.nupkg"
          dotnet nuget push ./StripeWatch.nupkg

