on: push
jobs:
  build_for_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v4
        with:
          source-url: https://nuget.pkg.github.com/Golos1/index.json
          dotnet-version: 9.0.x
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_KEY}}
      - name: Publish
        run: dotnet publish --configuration Release --self-contained true -p:PublishSingleFile=true -o ${{ github.workspace }}/publish
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env: 
          GITHUB_TOKEN: ${{secrets.RELEASE_TOKEN}}
        with:
          tag_name: Ubuntu-x64.${{github.run_number}}
          release_name: Ubuntu-x64.${{github.run_number}}
          draft: false
          prerelease: false
      - name: check release directory
        run: ls ${{ github.workspace }}/publish
      - name: Upload Linux Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{secrets.RELEASE_TOKEN}}
        with:
          upload_url: ${{steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/publish/StripeWatch
          asset_name: StripeWatch-ubuntu-x64
          asset_content_type: application/octet-stream
  build_for_macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Publish
        run: dotnet publish --configuration Release -r osx-arm64 --self-contained true -p:PublishSingleFile=true -o ${{ github.workspace }}/publish
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{secrets.RELEASE_TOKEN}}
        with:
          tag_name: MacOS-arm64.${{github.run_number}}
          release_name: MacOS-arm64.${{github.run_number}}
          draft: false
          prerelease: false
      - name: check release directory
        run: ls ${{ github.workspace }}/publish
      - name: Upload MacOS Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{secrets.RELEASE_TOKEN}}
        with:
          upload_url: ${{steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/publish/StripeWatch
          asset_name: StripeWatch-macos-arm64
          asset_content_type: application/octet-stream
  build_for_windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Publish
        run: dotnet publish --configuration Release -r win-x64 --self-contained true -p:PublishSingleFile=true -o ${{ github.workspace }}/publish
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{secrets.RELEASE_TOKEN}}
        with:
          tag_name: Windows-x64.${{github.run_number}}
          release_name: Windows-x64.${{github.run_number}}
          draft: false
          prerelease: false
      - name: check release directory
        run: ls ${{ github.workspace }}/publish
      - name: Upload Windows Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{secrets.RELEASE_TOKEN}}
        with:
          upload_url: ${{steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/publish/StripeWatch.exe
          asset_name: StripeWatch.exe
          asset_content_type: application/octet-stream