on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v4
        with:
          source-url: https://nuget.pkg.github.com/Golos1/index.json
          dotnet-version: 9.0.x
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_KEY}}
      - name: Publish
        run: dotnet publish --configuration Release --self-contained true -p:PublishSingleFile=true -o ${{ github.workspace }}/publish
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env: 
          GITHUB_TOKEN: ${{secrets.RELEASE_TOKEN}}
        with:
          tag_name: v${{github.ref}}
          release_name: Release ${{github.ref}}
          draft: false
          prerelease: false
      - name: Upload Windows Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{secrets.RELEASE_TOKEN}}
        with: 
          upload_url: ${{steps.create_release.outputs.upload_url }}
          asset_path: ./publish/StripeWatch.exe
          asset_name: StripeWatch.exe
          asset_content_type: application/octet-stream
      - name: Upload Linux/Macos Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{secrets.RELEASE_TOKEN}}
        with:
          upload_url: ${{steps.create_release.outputs.upload_url }}
          asset_path: ./publish/StripeWatch
          asset_name: StripeWatch
          asset_content_type: application/octet-stream
